name: djira_client
description: Dart client for djira
version: 1.0.7
repository: https://github.com/oasisMystre/djira_client_dart

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  uuid:  ^3.0.0
  json_annotation: ^4.8.1
  socket_io_client: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6